# Generated by Django 2.2.5 on 2019-09-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20190905_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.TextField(),
        ),
    ]
